// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using velotech.Models;

namespace velotech.Migrations
{
    [DbContext(typeof(CadastroContext))]
    partial class CadastroContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("velotech.Models.Cadastro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CpfCnpj");

                    b.Property<int>("Documento");

                    b.Property<string>("Emissor");

                    b.Property<string>("Mae");

                    b.Property<DateTime>("Nascimento");

                    b.Property<string>("Nome");

                    b.Property<string>("Pai");

                    b.Property<string>("Rg");

                    b.HasKey("Id");

                    b.ToTable("Cadastros");
                });

            modelBuilder.Entity("velotech.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CadastroId");

                    b.Property<string>("Nome");

                    b.Property<int>("VeloRefId");

                    b.HasKey("Id");

                    b.HasIndex("CadastroId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("velotech.Models.Cliente", b =>
                {
                    b.HasOne("velotech.Models.Cadastro")
                        .WithMany("Clientes")
                        .HasForeignKey("CadastroId");
                });
#pragma warning restore 612, 618
        }
    }
}
